export const TODO_ITEM_SUCCESS = 'todo.TODO_ITEM_SUCCESS';
export const TODO_ITEM_FAILURE = 'todo.TODO_ITEM_FAILURE';
export const UPDATE_TODO_ITEM_SUCCESS = 'todo.UPDATE_TODO_ITEM_SUCCESS';
export const UPDATE_TODO_ITEM_FAILURE = 'todo.UPDATE_TODO_ITEM_FAILURE';
export const FETCH_TODO_ITEM_SUCCESS = 'todo.FETCH_TODO_ITEM_SUCCESS';
export const FETCH_TODO_ITEM_FAILURE = 'todo.FETCH_TODO_ITEM_FAILURE';